TOOLS = tools/funkinisopak tools/funkinarcpak tools/funkinchartpak \
	tools/funkintimconv tools/psxavenc tools/xainterleave \
	tools/funkintimfixup

all: $(TOOLS)

$(TOOLS):
	cd $@ && $(MAKE)

.PHONY: all $(TOOLS)
