name: ISO

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install libswscale-dev libavformat-dev libtinyxml2-dev gcc-mipsel-linux-gnu g++-mipsel-linux-gnu binutils-mipsel-linux-gnu

    - name: Install mkpsxiso
      run: |
        wget https://github.com/Lameguy64/mkpsxiso/releases/download/v2.03/mkpsxiso-2.03-Linux.deb
        sudo dpkg -i mkpsxiso-2.03-Linux.deb

    - name: Copy PsyQ
      run: |
        cd mips
        wget http://psx.arthus.net/sdk/Psy-Q/psyq-4_7-converted-light.zip
        unzip psyq-4_7-converted-light.zip
        mv psyq-4_7-converted psyq
        
    - name: Compile tools
      run: |
        make -f Makefile.tools
        make -f Makefile.tim
        make -f Makefile.xa
        make -f Makefile.cht
      
    - name: Compile PSXFunkin
      run: make
      
    - name: Make ISO
      run: |
        wget https://archive.org/download/psyq-sdk/PSYQ_SDK.zip/psyq%2Fcdgen%2FLCNSFILE%2FLICENSEA.DAT
        mkpsxiso -y funkin.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: EXE
        path: ./funkin.ps-exe
